view: orders {
  sql_table_name:
    `astrafy-bch-xlofi-2026.astrafy_analytics.fct_orders_segmented`
  ;;

  set: order_details {
    fields: [
      order_id,
      customer_id,
      order_date,
      order_net_sales,
      qty_product,
      prior_orders_12m,
      order_segmentation,
      has_complete_12_month_history
    ]
  }

  dimension: order_id {
    primary_key: yes
    type: number
    sql: ${TABLE}.order_id ;;

    label: "Order ID"
    description: "Unique identifier of an order."

    hidden: yes
  }

  dimension: customer_id {
    type: number
    sql: ${TABLE}.customer_id ;;

    label: "Customer ID"
    description: "Unique identifier of the customer who placed the order."

    group_label: "Customer"
  }

  dimension_group: order {
    type: time

    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]

    datatype: date
    convert_tz: no

    sql: ${TABLE}.order_date ;;

    label: "Order"
    description: "Calendar date on which the order was placed."
  }

  dimension: order_net_sales {
    type: number
    sql: ${TABLE}.order_net_sales ;;

    label: "Order Net Sales"
    description: "Net revenue associated with the individual order."

    value_format: "€#,##0.00"
    group_label: "Revenue"
  }

  dimension: qty_product {
    type: number
    sql: ${TABLE}.qty_product ;;

    label: "Product Units"
    description: "Total quantity of product units included in the order."

    synonyms: [
      "product quantity",
      "number of products",
      "units purchased",
      "items purchased"
    ]

    group_label: "Products"
  }

  dimension: prior_orders_12m {
    type: number
    sql: ${TABLE}.prior_orders_12m ;;

    label: "Prior Orders — 12 Months"

    description: "
      Number of orders placed by the customer on earlier calendar
      dates during the 12 months preceding the current order.
    "

    group_label: "Customer Segmentation"
  }

  dimension: order_segmentation {
    type: string
    sql: ${TABLE}.order_segmentation ;;

    label: "Customer Order Segment"

    description: "
      Segment assigned to the order using the customer's preceding
      12-month order history. New means zero prior orders, Returning
      means one to three prior orders, and VIP means four or more.
    "

    synonyms: [
      "customer segment",
      "customer type",
      "order segment",
      "new returning VIP"
    ]

    group_label: "Customer Segmentation"
  }

  dimension: has_complete_12_month_history {
    type: yesno
    sql: ${TABLE}.has_complete_12_month_history ;;

    label: "Complete 12-Month History"

    description: "
      Indicates whether the supplied data covers the complete
      12-month period preceding the order.
    "

    group_label: "Customer Segmentation"
  }

  measure: order_count {
    type: count

    label: "Order Count"
    description: "Number of unique orders."

    synonyms: [
      "number of orders",
      "orders",
      "purchase count"
    ]

    drill_fields: [order_details*]
  }

  measure: total_net_revenue {
    type: sum
    sql: ${order_net_sales} ;;

    label: "Net Revenue"
    description: "Total net revenue generated by the selected orders."

    synonyms: [
      "revenue",
      "sales",
      "net sales",
      "turnover"
    ]

    value_format: "€#,##0.00"
    drill_fields: [order_details*]
  }

  measure: average_order_value {
    type: average
    sql: ${order_net_sales} ;;

    label: "Average Order Value"
    description: "Average net revenue generated per order."

    synonyms: [
      "AOV",
      "average basket value",
      "average purchase value"
    ]

    value_format: "€#,##0.00"
    drill_fields: [order_details*]
  }

  measure: unique_customers {
    type: count_distinct
    sql: ${customer_id} ;;

    label: "Unique Customers"
    description: "Number of distinct customers who placed an order."

    synonyms: [
      "customer count",
      "number of customers",
      "distinct customers"
    ]

    drill_fields: [customer_id]
  }

  measure: average_products_per_order {
    type: average
    sql: ${qty_product} ;;

    label: "Average Product Units per Order"

    description: "
      Average quantity of product units contained in an order.
      This uses total product quantity rather than distinct products.
    "

    synonyms: [
      "average products per order",
      "average items per basket",
      "average units per order"
    ]

    value_format: "0.00"
    drill_fields: [order_details*]
  }

  # ------------------------------------------------------------------
  # Segment performance
  # ------------------------------------------------------------------

  measure: new_order_count {
    type: count
    filters: [order_segmentation: "New"]

    label: "New Customer Orders"
    description: "Number of orders classified as New."

    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: returning_order_count {
    type: count
    filters: [order_segmentation: "Returning"]

    label: "Returning Customer Orders"
    description: "Number of orders classified as Returning."

    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: vip_order_count {
    type: count
    filters: [order_segmentation: "VIP"]

    label: "VIP Customer Orders"
    description: "Number of orders classified as VIP."

    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: new_net_revenue {
    type: sum
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "New"]

    label: "New Customer Net Revenue"
    description: "Net revenue generated by orders classified as New."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: returning_net_revenue {
    type: sum
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "Returning"]

    label: "Returning Customer Net Revenue"
    description: "Net revenue generated by orders classified as Returning."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: vip_net_revenue {
    type: sum
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "VIP"]

    label: "VIP Customer Net Revenue"
    description: "Net revenue generated by orders classified as VIP."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: new_average_order_value {
    type: average
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "New"]

    label: "New Customer Average Order Value"
    description: "Average net revenue per order classified as New."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: returning_average_order_value {
    type: average
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "Returning"]

    label: "Returning Customer Average Order Value"
    description: "Average net revenue per order classified as Returning."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: vip_average_order_value {
    type: average
    sql: ${order_net_sales} ;;
    filters: [order_segmentation: "VIP"]

    label: "VIP Customer Average Order Value"
    description: "Average net revenue per order classified as VIP."

    value_format: "€#,##0.00"
    group_label: "Segment Performance"
    drill_fields: [order_details*]
  }

  measure: new_revenue_share {
    type: number
    sql: SAFE_DIVIDE(${new_net_revenue}, ${total_net_revenue}) ;;

    label: "New Customer Revenue Share"
    description: "Share of net revenue generated by orders classified as New."

    value_format_name: percent_1
    group_label: "Segment Performance"
  }

  measure: returning_revenue_share {
    type: number
    sql: SAFE_DIVIDE(${returning_net_revenue}, ${total_net_revenue}) ;;

    label: "Returning Customer Revenue Share"
    description: "Share of net revenue generated by orders classified as Returning."

    value_format_name: percent_1
    group_label: "Segment Performance"
  }

  measure: vip_revenue_share {
    type: number
    sql: SAFE_DIVIDE(${vip_net_revenue}, ${total_net_revenue}) ;;

    label: "VIP Customer Revenue Share"
    description: "Share of net revenue generated by orders classified as VIP."

    value_format_name: percent_1
    group_label: "Segment Performance"
  }
}
