view: order_lines {
  sql_table_name: `astrafy-bch-xlofi-2026.astrafy_analytics.fct_order_lines` ;;

  set: product_line_details {
    fields: [
      order_line_key,
      order_id,
      customer_id,
      order_date,
      product_id,
      product_quantity,
      line_net_sales,
      order_segmentation,
      prior_orders_12m,
      has_complete_12_month_history
    ]
  }

  dimension: order_line_key {
    primary_key: yes
    type: string

    sql:
      concat(
        cast(${TABLE}.order_id as string),
        '-',
        cast(${TABLE}.product_id as string)
      )
    ;;

    label: "Order Product Key"
    description: "Unique technical key formed from the order and product identifiers."

    hidden: yes
  }

  dimension: order_id {
    type: number
    sql: ${TABLE}.order_id ;;

    label: "Order ID"
    description: "Identifier of the order containing the product."

    hidden: yes
  }

  dimension: customer_id {
    type: number
    sql: ${TABLE}.customer_id ;;

    label: "Customer ID"
    description: "Identifier of the customer who placed the order."

    group_label: "Customer"
  }

  dimension_group: order {
    type: time

    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]

    datatype: date
    convert_tz: no

    sql: ${TABLE}.order_date ;;

    label: "Order"
    description: "Calendar date on which the order was placed."
  }

  dimension: product_id {
    type: number
    sql: ${TABLE}.product_id ;;

    label: "Product ID"
    description: "Identifier of the product included in the order."

    synonyms: [
      "product",
      "item",
      "product identifier",
      "item identifier"
    ]

    group_label: "Product"
  }

  dimension: product_quantity {
    type: number
    sql: ${TABLE}.product_quantity ;;

    label: "Product Units"
    description: "Number of units sold for this product within the order."

    synonyms: [
      "quantity",
      "units sold",
      "items sold",
      "product quantity"
    ]

    group_label: "Product"
  }

  dimension: line_net_sales {
    type: number
    sql: ${TABLE}.line_net_sales ;;

    label: "Product Net Sales"
    description: "Net revenue generated by this product line within the order."

    synonyms: [
      "product revenue",
      "line revenue",
      "product sales",
      "line net sales"
    ]

    value_format: "€#,##0.00"
    group_label: "Revenue"
  }

  dimension: prior_orders_12m {
    type: number
    sql: ${TABLE}.prior_orders_12m ;;

    label: "Prior Orders — 12 Months"

    description: "
      Number of orders placed by the customer on earlier calendar
      dates during the 12 months preceding this order.
    "

    group_label: "Customer Segmentation"
  }

  dimension: order_segmentation {
    type: string
    sql: ${TABLE}.order_segmentation ;;

    label: "Customer Order Segment"

    description: "
      Segment assigned to the order using the customer's preceding
      12-month order history. New means zero prior orders, Returning
      means one to three, and VIP means four or more.
    "

    synonyms: [
      "customer segment",
      "customer type",
      "order segment",
      "new returning VIP"
    ]

    group_label: "Customer Segmentation"
  }

  dimension: has_complete_12_month_history {
    type: yesno
    sql: ${TABLE}.has_complete_12_month_history ;;

    label: "Complete 12-Month History"

    description: "
      Indicates whether the available source data covers the complete
      12-month period preceding the order.
    "

    group_label: "Customer Segmentation"
  }

  measure: product_line_count {
    type: count

    label: "Product Line Count"
    description: "Number of order-product rows."

    synonyms: [
      "number of product lines",
      "line count"
    ]

    drill_fields: [product_line_details*]
  }

  measure: order_count {
    type: count_distinct
    sql: ${order_id} ;;

    label: "Order Count"
    description: "Number of distinct orders containing the selected products."

    synonyms: [
      "number of orders",
      "orders",
      "purchase count"
    ]

    drill_fields: [product_line_details*]
  }

  measure: unique_products {
    type: count_distinct
    sql: ${product_id} ;;

    label: "Unique Products"
    description: "Number of distinct products sold."

    synonyms: [
      "product count",
      "number of products",
      "distinct products"
    ]

    drill_fields: [product_id]
  }

  measure: unique_customers {
    type: count_distinct
    sql: ${customer_id} ;;

    label: "Unique Customers"
    description: "Number of distinct customers purchasing the selected products."

    synonyms: [
      "customer count",
      "number of customers",
      "distinct customers"
    ]

    drill_fields: [customer_id]
  }

  measure: total_units_sold {
    type: sum
    sql: ${product_quantity} ;;

    label: "Product Units Sold"
    description: "Total quantity of product units sold."

    synonyms: [
      "units sold",
      "quantity sold",
      "items sold",
      "sales volume"
    ]

    value_format: "#,##0"
    drill_fields: [product_line_details*]
  }

  measure: total_product_revenue {
    type: sum
    sql: ${line_net_sales} ;;

    label: "Product Net Revenue"
    description: "Total net revenue generated by product sales lines."

    synonyms: [
      "product revenue",
      "revenue",
      "sales",
      "net sales",
      "turnover"
    ]

    value_format: "€#,##0.00"
    drill_fields: [product_line_details*]
  }

  measure: average_line_revenue {
    type: average
    sql: ${line_net_sales} ;;

    label: "Average Product-Line Revenue"
    description: "Average net revenue generated by an order-product line."

    value_format: "€#,##0.00"
    drill_fields: [product_line_details*]
  }

  measure: average_units_per_line {
    type: average
    sql: ${product_quantity} ;;

    label: "Average Units per Product Line"
    description: "Average quantity sold per order-product line."

    value_format: "0.00"
    drill_fields: [product_line_details*]
  }
}
